#ifndef RESOURCE_H
#define RESOURCE_H

#define IDD_ABOUT_DIALOG 101
#define IDC_STATIC       -1
#define IDI_ICON1        102
#define IDC_ABOUT_ICON   103
#define IDD_SETTINGS_DIALOG 104

#define IDC_SETTINGS_MIDI_MODE       1100
#define IDC_SETTINGS_MIDI_VOLUME     1101
#define IDC_SETTINGS_MLOOK           1102
#define IDC_SETTINGS_PCM_ENABLED     1103
#define IDC_SETTINGS_PCM_VOLUME      1104
#define IDC_SETTINGS_RAYCAST_FOV     1105
#define IDC_SETTINGS_SUPERSAMPLE     1106
#define IDC_SETTINGS_RENDERER        1107
#define IDC_SETTINGS_LABEL_MIDI_MODE 1110
#define IDC_SETTINGS_LABEL_MIDI_VOL  1111
#define IDC_SETTINGS_LABEL_MLOOK     1112
#define IDC_SETTINGS_LABEL_PCM_VOL   1113
#define IDC_SETTINGS_LABEL_FOV       1114
#define IDC_SETTINGS_LABEL_SS        1115
#define IDC_SETTINGS_LABEL_RENDERER  1116

#define IDB_SYSINFO_BG   201

#endif // RESOURCE_H
