; Segment emission manifest: entries are provisional; bytes retain original order.
%include "src/data/code_5_header_and_unowned_prefix.asm"
%include "src/functions/unknown/code_5_0004_unknown.asm"
%include "src/functions/unknown/code_5_04b0_unknown.asm"
%include "src/functions/unknown/code_5_05be_unknown.asm"
%include "src/functions/unknown/code_5_06f2_unknown.asm"
%include "src/functions/unknown/code_5_20b4_unknown.asm"
%include "src/functions/unknown/code_5_222a_unknown.asm"
%include "src/functions/unknown/code_5_4452_unknown.asm"
%include "src/functions/unknown/code_5_4564_unknown.asm"
%include "src/functions/unknown/code_5_45f6_unknown.asm"
%include "src/functions/unknown/code_5_6b82_unknown.asm"
%include "src/functions/unknown/code_5_6c16_unknown.asm"
%include "src/functions/unknown/code_5_6c18_unknown.asm"
%include "src/functions/unknown/code_5_6c7e_unknown.asm"
